-- ============================================
-- USE DATABASE
-- ============================================

USE transitops;

-- ============================================
-- ROLES
-- ============================================

INSERT INTO roles (role_name, description) VALUES
('Fleet Manager', 'Manages fleet operations'),
('Driver', 'Assigned to trips'),
('Safety Officer', 'Monitors driver and vehicle safety'),
('Financial Analyst', 'Views reports and expenses');

-- ============================================
-- USERS
-- Password for all users: Password@123
-- Replace the hash with a bcrypt hash generated by your app.
-- ============================================

INSERT INTO users
(role_id, full_name, email, password_hash, phone)
VALUES

(1,
'Fleet Manager',
'manager@transitops.com',
'$2b$10$ReplaceWithBcryptHash',
'9876543210'),

(2,
'John Driver',
'driver1@transitops.com',
'$2b$10$ReplaceWithBcryptHash',
'9876543211'),

(2,
'David Driver',
'driver2@transitops.com',
'$2b$10$ReplaceWithBcryptHash',
'9876543212'),

(3,
'Safety Officer',
'safety@transitops.com',
'$2b$10$ReplaceWithBcryptHash',
'9876543213'),

(4,
'Finance Analyst',
'finance@transitops.com',
'$2b$10$ReplaceWithBcryptHash',
'9876543214');

-- ============================================
-- DRIVERS
-- ============================================

INSERT INTO drivers
(user_id,
license_number,
license_category,
license_expiry,
safety_score,
status)
VALUES

(2,
'DL123456789',
'Heavy',
'2028-12-31',
95.50,
'AVAILABLE'),

(3,
'DL987654321',
'Heavy',
'2027-08-15',
92.00,
'AVAILABLE');

-- ============================================
-- VEHICLES
-- ============================================

INSERT INTO vehicles
(
registration_number,
vehicle_name,
manufacturer,
model,
vehicle_year,
vehicle_type,
fuel_type,
max_load_capacity,
odometer,
acquisition_cost,
purchase_date,
status
)

VALUES

(
'TS09AB1234',
'Ashok Leyland Truck',
'Ashok Leyland',
'4825',
2023,
'Truck',
'Diesel',
15000,
35000,
2800000,
'2023-05-15',
'AVAILABLE'
),

(
'TS09CD5678',
'Tata Ace',
'Tata',
'Gold',
2022,
'Mini Truck',
'Diesel',
1200,
28000,
650000,
'2022-02-18',
'AVAILABLE'
),

(
'TS09EF9012',
'Mahindra Bolero',
'Mahindra',
'Pickup',
2024,
'Van',
'Diesel',
1800,
8000,
980000,
'2024-01-10',
'AVAILABLE'
);

-- ============================================
-- ROUTES
-- ============================================

INSERT INTO routes
(
source,
destination,
distance,
estimated_duration
)

VALUES

(
'Hyderabad',
'Warangal',
150,
180
),

(
'Hyderabad',
'Vijayawada',
275,
330
),

(
'Hyderabad',
'Bengaluru',
575,
540
);

-- ============================================
-- TRIPS
-- ============================================

INSERT INTO trips
(
trip_code,
route_id,
vehicle_id,
driver_id,
cargo_weight,
planned_distance,
actual_distance,
start_time,
end_time,
revenue,
status,
created_by
)

VALUES

(
'TRIP001',
1,
1,
1,
8000,
150,
150,
'2026-07-12 08:00:00',
'2026-07-12 11:00:00',
45000,
'COMPLETED',
1
),

(
'TRIP002',
2,
2,
2,
900,
275,
NULL,
'2026-07-13 07:00:00',
NULL,
65000,
'DISPATCHED',
1
);

-- ============================================
-- MAINTENANCE
-- ============================================

INSERT INTO maintenance_logs
(
vehicle_id,
maintenance_type,
description,
maintenance_cost,
start_date,
end_date,
status
)

VALUES

(
3,
'SERVICE',
'General vehicle servicing',
7500,
'2026-07-01',
'2026-07-02',
'COMPLETED'
);

-- ============================================
-- FUEL LOGS
-- ============================================

INSERT INTO fuel_logs
(
vehicle_id,
trip_id,
odometer_reading,
fuel_liters,
fuel_cost,
fuel_station,
fuel_date
)

VALUES

(
1,
1,
35150,
40,
3800,
'Indian Oil',
'2026-07-12'
),

(
2,
2,
28120,
30,
2850,
'HP Fuel Station',
'2026-07-13'
);

-- ============================================
-- EXPENSES
-- ============================================

INSERT INTO expenses
(
vehicle_id,
trip_id,
expense_type,
amount,
description,
expense_date
)

VALUES

(
1,
1,
'TOLL',
1200,
'National Highway Toll',
'2026-07-12'
),

(
2,
2,
'PARKING',
350,
'Warehouse Parking',
'2026-07-13'
);

-- ============================================
-- VEHICLE DOCUMENTS
-- ============================================

INSERT INTO vehicle_documents
(
vehicle_id,
document_type,
file_url,
expiry_date
)

VALUES

(
1,
'Insurance',
'https://example.com/insurance1.pdf',
'2027-05-20'
),

(
2,
'Registration',
'https://example.com/rc2.pdf',
'2032-02-18'
);

-- ============================================
-- NOTIFICATIONS
-- ============================================

INSERT INTO notifications
(
user_id,
title,
message
)

VALUES

(
1,
'Trip Completed',
'Trip TRIP001 has been completed successfully.'
),

(
2,
'New Trip Assigned',
'You have been assigned to TRIP002.'
);

-- ============================================
-- AUDIT LOGS
-- ============================================

INSERT INTO audit_logs
(
user_id,
action,
table_name,
record_id
)

VALUES

(
1,
'CREATE',
'vehicles',
1
),

(
1,
'CREATE',
'trips',
1
);